### ISSUE TITLE
about: Ссылка "Встречи" ведёт на эту же страницу

### ISSUE THREAD

**Issue by artyom-poptsov** [defcon-nn/defcon-nn.github.io#21]
Привет,

похоже, что ссылка "Встречи" вверху страницы [about.html](http://defcon-nn.ru/about.html) ведёт обратно на эту же страницу.

-- Артём

**Comment by GnuriaN** [comment]
Подтверждаю Я и "форк-переделка для себя" с которым я играюсь =)

**исходная страница:** http://defcon-nn.ru/about.html
`ссылка "Встречи" вверху страницы about.html ведёт обратно на эту же страницу.`

Формирование ссылки идет в `default.html`
```HTML
<a href="{{ site.baseurl }}">Меню 1</a>
```

При этом `site.baseurl` должен браться из `_config.yml` но для любой страницы, исходя из моих тестов, ведет на страницу на которой сейчас находимся.

**Comment by GnuriaN** [comment]
Как вариант, сделал у себя так:
```HTML
<a href="{{ "/index.html" | prepend: site.baseurl }}">Меню 1</a>
```
И получаю ссылку для перехода.
еще один вариант:
```HTML
<a href="{{ "/" | prepend: site.baseurl }}">Меню 1</a>
```
Но это костыль (((

**Comment by artyom-poptsov** [comment]
Судя по всему, проблема исправлена в e8af0bfd86; на сайте тоже проблема решена.
Закрываю issue.

-- Артём

**Comment by wsnark** [comment]
Ага, Никита пофиксил - в том коммите строчка 20.
